GET http://localhost:5000/api/books


###
POST http://localhost:5000/api/books
Content-Type: application/json


{
    "name": "Truyen Kieu",
    "author": "Nguyen Du",
    "type": "Poetry stories"
}

###
GET http://localhost:5000/api/books/656f44f4cee3dd4e554e9bba


###
PUT  http://localhost:5000/api/books/1
Content-Type: application/json


{
    "name": "Dung"
}

###
DELETE  http://localhost:5000/api/books/656f5550af1d4e5691ddef3b


###
PATCH   http://localhost:5000/api/books/restore/656f5550af1d4e5691ddef3b